services:
  mongo:
    image: mongo:7.0
    container_name: p5_mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      # Variables d'environnement pour l'authentification
     
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
      # Variables pour le script d'init (user applicatif)
      MONGO_APP_USER: ${MONGO_APP_USER}
      MONGO_APP_PASSWORD: ${MONGO_APP_PASSWORD}
    volumes:
      - mongo-data:/data/db
      # Script d'init (exécuté au premier démarrage)
      - ./mongo-init:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "--eval", "db.runCommand('ping').ok"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  app:
    build: .
    container_name: p5_app
    depends_on:
      mongo:
        condition: service_healthy
    environment:
      # URI avec authentification
      # Format: mongodb://USER:PASSWORD@HOST:PORT/DATABASE?authSource=DATABASE
      MONGO_URI: mongodb://${MONGO_APP_USER}:${MONGO_APP_PASSWORD}@mongo:27017/${MONGO_DATABASE}?authSource=${MONGO_DATABASE}
    volumes:
      - ./:/app
    working_dir: /app

volumes:
  mongo-data:
